// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.19;

import { IRNSource } from "src/rnsources/interfaces/IRNSource.sol";

interface IAPI3DaoRNSource is IRNSource {
    /// @return Address of the airnode provider (addresses currently could be found here
    ///            https://docs.api3.org/reference/qrng/providers.html)
    function airnodeProvider() external view returns (address);

    /// @return endpointIdUint256 value from airnode provider that is chosen (values and address providers currently
    ///             could be found here https://docs.api3.org/reference/qrng/providers.html)
    function endpointIdUint256() external view returns (bytes32);

    /// @return Address of the sponsor wallet that is generated by command
    /*      npx @api3/airnode-admin derive-sponsor-wallet-address \
                --airnode-xpub <Use xpub from airnode provider that is chosen> \
                --airnode-address <Use airnode provider address that is chosen> \
                --sponsor-address <Use future contract address were contract will be deployed>
    */
    function sponsorWallet() external view returns (address);
}
